# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="TouristSpot", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("content_id", models.CharField(max_length=50, unique=True)),
            ("name", models.CharField(max_length=255)),
            ("category", models.CharField(choices=[("ATTRACTION", "관광지"), ("RESTAURANT", "맛집"), ("LODGING", "숙박"), ("FESTIVAL", "축제")], max_length=20)),
            ("address", models.CharField(max_length=500)), ("description", models.TextField()),
            ("hours", models.CharField(blank=True, max_length=500)),
            ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
            ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
            ("sigungu", models.CharField(blank=True, max_length=100)),
            ("parking_available", models.BooleanField(blank=True, null=True)),
            ("synced_at", models.DateTimeField()),
        ]),
        migrations.CreateModel(name="TouristSpotImage", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("image_url", models.URLField(max_length=1000)),
            ("is_primary", models.BooleanField(default=False)),
            ("order", models.PositiveSmallIntegerField(default=0)),
            ("spot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="places.touristspot")),
        ], options={"ordering": ["order", "id"]}),
    ]

