# Generated by Django 5.2.17 on 2026-08-10 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_notification_enabled', models.BooleanField(default=True)),
                ('golden_hour_notification_enabled', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('ko', '한국어'), ('en', 'English'), ('ja', '日本語'), ('zh', '中文')], default='ko', max_length=2)),
                ('location_permission_granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
