# Generated by Django 5.2.16 on 2026-07-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('signup', '회원가입'), ('password_reset', '비밀번호 재설정')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose', 'code', 'is_used'], name='accounts_evc_lookup_idx'), models.Index(fields=['is_used', 'expires_at'], name='accounts_evc_expiry_idx')],
            },
        ),
    ]
