# Generated by Django 5.2.16 on 2026-07-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationcode'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('kakao', 'Kakao')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_id'), name='accounts_user_provider_provider_id_unique'),
        ),
    ]
