# Generated by Django 5.2.17 on 2026-08-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_provider_user_provider_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
