# Generated by Django 5.2.17 on 2026-08-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
