# Generated by Django 5.2.17 on 2026-08-09 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSummaryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('positive_keywords', models.JSONField(default=list)),
                ('negative_keywords', models.JSONField(default=list)),
                ('review_count_at_calc', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_summary_cache', to='places.touristspot')),
            ],
        ),
    ]
