# Generated by Django 5.2.17 on 2026-08-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='free_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='time_available',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
