# Generated by Django 5.2.17 on 2026-08-09 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(choices=[('46110', '목포시'), ('46130', '여수시'), ('46150', '순천시'), ('46170', '나주시'), ('46230', '광양시'), ('46710', '담양군'), ('46720', '곡성군'), ('46730', '구례군'), ('46770', '고흥군'), ('46780', '보성군'), ('46790', '화순군'), ('46800', '장흥군'), ('46810', '강진군'), ('46820', '해남군'), ('46830', '영암군'), ('46840', '무안군'), ('46860', '함평군'), ('46870', '영광군'), ('46880', '장성군'), ('46890', '완도군'), ('46900', '진도군'), ('46910', '신안군')], max_length=5)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'city_code'), name='gamification_stamp_user_city_code_unique')],
            },
        ),
    ]
